server:
  port: ${configServerPort}
spring:
  cloud:
    config:
      server:
        git:
          uri: ${uri}
          default-label: master
          ignore-local-ssh-settings: true
          private-key: ${privateKey}

